''
'' These colours should be based on the colours used in style.css
''

''
'' Note that all <text> elements will be styled by css which overrides any of these values
''  (that includes participant names, arrow text etc)
''

!$BACKGROUND_COLOR  = "#fff"
!$BACKGROUND_COLOR_HIGHLIGHT  = "yellow"
!$LINE_COLOR_PRIMARY  = "#7d8590"
!$LINE_COLOR_SECONDARY  = "slategrey"
!$TEXT_COLOR_PRIMARY  = "#656d76"
!$TEXT_COLOR_SECONDARY  = "#8392A2FF"
!$TEXT_COLOR_HYPERLINK  = "#656d76"

<style>
  root {
    FontColor $TEXT_COLOR_SECONDARY
    HyperLinkColor $TEXT_COLOR_HYPERLINK
    BackgroundColor $BACKGROUND_COLOR
    LineThickness 1.5
    LineColor $LINE_COLOR_PRIMARY
    RoundCorner 5
    Margin 10
    Padding 6
  }
  title {
    LineThickness 0
    FontColor $TEXT_COLOR_PRIMARY
  }
  note {
    BackGroundColor $BACKGROUND_COLOR_HIGHLIGHT
    LineThickness 0.5
    FontColor $TEXT_COLOR_PRIMARY
  }
  lifeline {
    LineThickness 1
    LineColor $LINE_COLOR_SECONDARY
  }
  arrow {
    LineThickness 1.5
  }
</style>
