
' relationships with lsd-core to help with the order of updates when lsd-core changes

@startuml
title Dependencies on lsd-core

component "lsd-core"#royalblue
component "lsd-junit5"#lightgreen
component "lsd-cucumber"#lightgreen
component "lsd-distributed-generator"#lightgreen
component "lsd-interceptors"#orange
component "lsd-distributed-interceptors"#orange
component "lsd-distributed-generator-ui"#orange
component "lsd-kotlin-cucumber-example"#orange

[lsd-junit5] -[#lightgreen]-> [lsd-core] : -[api]

[lsd-cucumber] -[#lightgreen]-> [lsd-core] : -[api]
[lsd-interceptors] -[#lightgreen]-> [lsd-core] : -[impl]

[lsd-distributed-generator-ui] -[#orange]-> [lsd-distributed-generator] : -[impl]
[lsd-distributed-generator] -[#lightgreen]-> [lsd-core] : -[api]

[lsd-distributed-interceptors] -[#orange]-> [lsd-distributed-generator] : -[test]
[lsd-distributed-interceptors] -[#orange]-> [lsd-distributed-generator-ui] : -[test]
[lsd-distributed-interceptors] -[#lightgreen]-> [lsd-core] : -[api]
[lsd-distributed-interceptors] -[#orange]-> [lsd-junit5] : -[test]
[lsd-interceptors] -[#orange]-> [lsd-junit5] : -[test]
[lsd-kotlin-cucumber-example] -[#orange]-> [lsd-cucumber] : -(dynamic\nversioning)
[lsd-kotlin-cucumber-example] -[#orange]-> [lsd-interceptors] : -(dynamic\nversioning)

hide unlinked

@enduml