name: Auto-approve Renovate PR
on:
  pull_request_target:
    branches:
      - main
      - master
jobs:
  renovate-auto-approve:
    uses: lsd-consulting/shared-workflows/.github/workflows/renovate-automerge.yml@main
    secrets: inherit
